### ISSUE TITLE
llvm-9999 doesn't work with multi arch

### ISSUE THREAD

**Issue by cb88** [FireBurn/Overlay#55]
The emerge fails with this... the gentoo ebuild however builds just fine I only noticed this as it defaulted to the one from this overlay. 

ninja: error: '/usr/lib32  /libffi.so', needed by 'lib32/libLLVMInterpreter.so.3.9.0svn', missing and no known rule to make it

Also the /usr/lib32 directory contains the folowing on my system. libffi-3.2.1/    libffi.so        libffi.so.6      libffi.so.6.0.4

**Comment by FireBurn** [comment]
Are you still having this issue? And is the repo up to date? I had that issue with the Gentoo build but the ebuild in my overlay is working just fine for me here
