### ISSUE TITLE
www-client/chromium-76.0.3809.25 failed to compile

### ISSUE THREAD

**Issue by shelterx** [FireBurn/Overlay#60]
See build.log
[build.zip](https://github.com/FireBurn/Overlay/files/3308766/build.zip)

EDIT:
Adding the following to vaapi_wrapper.cc seems to have fixed the problem, but I don't know if it's correct. A dirty fix I found regarding another vaapi compile issue.
```
#ifndef VA_FOURCC_I420
#define VA_FOURCC_I420 VA_FOURCC('I', '4', '2', '0')
#endif
```

**Comment by shelterx** [comment]
I've been using this for a while now and all seems ok, it also fixes the compile issue for newer chromium versions too.

**Comment by FireBurn** [comment]
It's just the one in portage with the vaapi patch from Arch Linux

**Comment by shelterx** [comment]
Builds fine with libva 2.4.0... so the stable 1.7.3 version currently in Gentoo is "too" old.

**Comment by FireBurn** [comment]
I'll try and figure out what the real minimum version is and get the ebuild updated

**Comment by FireBurn** [comment]
There's only libva-2.5 in portage now, so will close this
