### ISSUE TITLE
www-client/chromium-79.0.3928.4 failed to build

### ISSUE THREAD

**Issue by lukasz-h** [FireBurn/Overlay#61]
I am unable to build chromium 79.0.3928.4 there is a following error (repeated in few places):
`
../../base/logging.h:590:32: error: variable ‘true_if_passed’ of non-literal type ‘logging::CheckOpResult’ in ‘constexpr’ function
`

Full build log here: [build.log.gz](https://github.com/FireBurn/Overlay/files/3731548/build.log.gz)

Any advice?

**Comment by FireBurn** [comment]
Are you using clang to build? - that's what I'm using here (clang 10 specificily)

I'm just about finished with my chromium-79.0.3941.4 ebuild which should hopefully be ready within a few hours

**Comment by lukasz-h** [comment]
I have tested 79.0.3941.4, still without luck. The same error both in GCC and clang (but different than in my first post).

```
../../third_party/swiftshader/src/System/Linux/MemFd.hpp:25:11: error: expected identifier or '{'
namespace linux
          ^  
<built-in>:404:15: note: expanded from here  
#define linux 1
```

`gcc version 9.1.0 (Gentoo 9.1.0-r1 p1.1)`
`clang version 7.1.0 (tags/RELEASE_710/final)`

Full logs here: 
[build_clang.log.gz](https://github.com/FireBurn/Overlay/files/3736498/build_clang.log.gz)
[build_gcc.log.gz](https://github.com/FireBurn/Overlay/files/3736500/build_gcc.log.gz)

**Comment by FireBurn** [comment]
I didn't get that with clang-10

But I did notice this commit to the upstream swiftshader:

https://github.com/google/swiftshader/commit/fb632b91110cabce297c34b8c01ec8c931a10933

Might be worth seeing if you can apply it

**Comment by lukasz-h** [comment]
After applying that commit I was able to build it with clang-8, I didn't test with GCC. Thanks for support. I think it may be worth to add it to overlay.

**Comment by FireBurn** [comment]
Did you change that patch at all to get it to apply?

**Comment by FireBurn** [comment]
Ah just needed to update the paths

https://github.com/FireBurn/Overlay/commit/331f5e61d27234df824a431b0f3ecf52559df691
