### ISSUE TITLE
www-client/chromium-81.0.4000.3 fails video with wrong palette

### ISSUE THREAD

**Issue by skinkie** [FireBurn/Overlay#64]
![image](https://user-images.githubusercontent.com/502394/71590425-b0049d00-2b28-11ea-89cb-1a00ad07de2c.png)

**Comment by skinkie** [comment]
If hardware acceleration is disabled, this again turns back to normal.

**Comment by FireBurn** [comment]
The ebuild should install a dric config that disables 10bit configs

/usr/share/drirc.d/01-chromium.conf

What version of Mesa are you using?

It might be worth setting allow_rgb10_configs=false before running chromium to see if that fixes things

**Comment by skinkie** [comment]
I cannot reproduce the issue anymore. I did upgrade quite some packages, due to a cflag change. My mesa is media-libs/mesa-19.3.1.

I can confirm that the dric.d config file is there.

I am closing this bug.
