### ISSUE TITLE
Chrome 80+ has issues with several (big) websites over HTTPS

### ISSUE THREAD

**Issue by skinkie** [FireBurn/Overlay#65]
I have noticed since a few days that several big Dutch websites became unreachable using Chromium 80. For example https://nrc.nl/ (news) https://snsbank.nl (banking) https://omroepwest.nl/ (regional news). I have been in contact with the security team of the banking websites which became aware of the issue last week, but was still tracking down the cause. Reducing the MTU on my NIC allowed me to go to the banking website, but not to the others. There is a suggestion that this is caused by a Do not fragment bit set in Chrome, but I have not yet found any tickets regarding this. Has anyone heard of these issues?

**Comment by FireBurn** [comment]
I'm afraid that bug will need to go upstream https://bugs.chromium.org/ 

I've not noticed anything but I'll need to check next time I'm home, to help rule things out it might be worth trying the Chrome binary version or even try the windows dev stream to see if there is a problem with the code

**Comment by skinkie** [comment]
Does https://www.nrc.nl/ work for you using the latest Chromium?

**Comment by FireBurn** [comment]
No, I get:

This site can’t be reachedwww.nrc.nl unexpectedly closed the connection.
Try:

Checking the connection
Checking the proxy and the firewall
ERR_CONNECTION_CLOSED

**Comment by skinkie** [comment]
This is exactly what has happened for me since the upgrade. I have heard from a banking institution it was introduced there by a firewall/proxy/cache/ssl-terminator that would increase SSL packets over a certain limit, which they could fix. It would have affected the new Webkit-Edge as well. So I think this is a bug is HTTPS sources that is triggered by Chrome, but I am unaware where it is tracked.

**Comment by FireBurn** [comment]
I'm wondering if it's based on the user agent string

User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/82.0.4083.0 Safari/537.36

I tried spoofing it but to no avail, the site works fine on my Android phone

I tried a spoofer, but I keep seeing the above in the Request Headers

**Comment by FireBurn** [comment]
It might be worth reporting it upstream at crbug.com

**Comment by skinkie** [comment]
Interesting or not. Running on 81, it works now. I don't know if the servers have been fixed, or it is a Chrome fix.

**Comment by FireBurn** [comment]
Great news that it's fixed for you

If you're happy, then feel free to close this off
