### ISSUE TITLE
Chromium compilation (with LTO) takes more than 7GiB

### ISSUE THREAD

**Issue by skinkie** [FireBurn/Overlay#69]
Currently there is a check for free disk space for 7GiB, I would suggest to increase it to 8GiB. I am also under the impression that ebuild chormium.ebuild compile does **not** resume the compilation :(

**Comment by skinkie** [comment]
Conclusion; ninja restarts the counter of to be compiled objects. Thus the claim that it does not resume is invalid.
The total source dir is 6.9GB but for some reason that wasn't enough. Maybe this because of the 10% reservation?

**Comment by FireBurn** [comment]
Vaapi enabled chromium is now upstream in ::gentoo and will be retired from this overlay shortly
