### ISSUE TITLE
Chromium 85: pasting rich content

### ISSUE THREAD

**Issue by skinkie** [FireBurn/Overlay#70]
As of Chromium 85 I am not able to paste any images anymore in the browser. Does anyone else experience the same thing?

**Comment by FireBurn** [comment]
I'm not sure that's something I've ever tried to do

It might be worth reporting it upstream

**Comment by skinkie** [comment]
> I'm not sure that's something I've ever tried to do
> 
> It might be worth reporting it upstream

What for example does work now is creating a screenshot, and pasting it here on github.

**Comment by skinkie** [comment]
Fixed upstream: https://bugs.chromium.org/p/chromium/issues/detail?id=1088343
