### ISSUE TITLE
app-emulation/dxvk: Patch for recent changes to dxvk

### ISSUE THREAD

**Issue by TheGreatMcPain** [FireBurn/Overlay#72]
DXVK recently merged a [pull request](https://github.com/doitsujin/dxvk/pull/1886) that broke winelib again.

I've recently made a [patch](https://github.com/TheGreatMcPain/TheGreatMcPain-overlay/blob/master/app-emulation/dxvk-winelib/files/dxvk-wineopenxr.patch) that makes winelib build again.

**Comment by FireBurn** [comment]
Thanks for that

I switched to using -fpermissive locally

I'll test this out and add it in

Thanks

**Comment by FireBurn** [comment]
That's that patch merged

Do let me know if you come up with a better way of fixing this: https://github.com/TheGreatMcPain/TheGreatMcPain-overlay/blob/master/app-emulation/dxvk-winelib/files/dxvk-revert-handle-non-ascii.patch
