### ISSUE TITLE
polkit-0.119 with duktape?

### ISSUE THREAD

**Issue by jospezial** [FireBurn/Overlay#73]
Do you want to bump duktape-based polkit to 0.119 ?
see also https://aur.archlinux.org/cgit/aur.git/commit/?h=polkit-duktape&id=2d22260e2f0c657f23adb7b128c8f798266bf35c

**Comment by FireBurn** [comment]
I'll look at getting that sorted

**Comment by jospezial** [comment]
https://github.com/FireBurn/Overlay/commit/7347f7f4ba7583d6e90b562046c1aa979a91f771
Thank you.
Ebuild seems to work.
