### ISSUE TITLE
games-emulation/yuzu-9999 mbedcrypto

### ISSUE THREAD

**Issue by DouseMouse** [FireBurn/Overlay#76]
CMake Error at externals/CMakeLists.txt:42 (target_compile_options):
  Cannot specify compile options for target "mbedcrypto" which is not built
  by this project.
[build.log](https://github.com/FireBurn/Overlay/files/13763593/build.log)

**Comment by FireBurn** [comment]
Try the patches here:

https://github.com/FireBurn/PortageStuff/tree/master/patches/games-emulation/yuzu

Merry Christmas

**Comment by DouseMouse** [comment]
FAILED: src/video_core/CMakeFiles/video_core.dir/renderer_vulkan/vk_swapchain.cpp.o
[build.log](https://github.com/FireBurn/Overlay/files/13774279/build.log)

**Comment by FireBurn** [comment]
That should be it fixed now

**Comment by DouseMouse** [comment]
Was working again. Now I have another problem after a world update.
[build.log](https://github.com/FireBurn/Overlay/files/13830896/build.log)

**Comment by FireBurn** [comment]
Are you meaning to enable Qt6? I'll hazard a guess that something boost related (or maybe Qt) hasn't been rebuilt

If you don't need Qt6 try disabling it, to rule that out (I'm testing Plasma6 locally)

**Comment by DouseMouse** [comment]
Did an emptytree and it works again.
