### ISSUE TITLE
www-client/firefox: missing python module with python3.13

### ISSUE THREAD

**Issue by Username404-59** [FireBurn/Overlay#77]
USE flags are `-telemetry jumbo-build -geckodriver clang pgo openh264 system-png`
Building firefox fails on my machine because of the python `pipes` module being missing
I believe [it was removed in python3.13](https://docs.python.org/3.13/whatsnew/3.13.html#whatsnew313-pep594) so perhaps it would be wise to set the PYTHON_COMPAT maximum to 3.12 in the meantime?

**Comment by FireBurn** [comment]
Will do

**Comment by FireBurn** [comment]
That's it changed back to 3.12
